client_config_backend: file
# client_config_file: client_secrets.json
client_config:
  client_id: <client id>
  client_secret: <client secret>
#   auth_uri: {{str}}
#   token_uri: {{str}}
#   redirect_uri: {{str}}
#   revoke_uri: {{str}}

save_credentials: true
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: true

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install

# oauth_scope: {{list of str}}