version: "3.9"

services:
  postgres:
    image: postgres
    env_file:
      - .env

  django:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env